### ISSUE TITLE
Performance degradation with latest changes

### ISSUE THREAD

**Issue by dselivanov** [greg7mdp/sparsepp#31]
Hi @greg7mdp. Yesterday I noticed that my R package which uses `sparsepp` became super-slow. First I thought it is due to some my changes. But after more investigation I found that it is related to `sparsepp`, because it works fast when I use old version (1.5x faster that `std::unordered_map` as I reported in feedback) - https://github.com/greg7mdp/sparsepp/tree/0fb17374eb761e31c9256bce3a63e513e846d0bc.
In January I updated `sparsepp` to https://github.com/greg7mdp/sparsepp/tree/48fc88160011dff87030f992d7c0afc874c7350f and things became super slow (I think 10-100x). 

I use following function to hash `pair<uint32_t, uint32_t>` to `uint64_t`:
```c++
namespace std {
  template <>
  struct hash<std::pair<uint32_t, uint32_t>>
  {
    inline uint64_t operator()(const std::pair<uint32_t, uint32_t>& k) const
    {
      return (uint64_t) k.first << 32 | k.second;
    }
  };
}
```
In my case it should not produce any collisions.

**Comment by greg7mdp** [comment]
Hi @dselivanov,

Sorry about the issue. I need to keep a file listing the changes in sparsepp and the possible issues.

The performance degradation you see is because your hash function is creating a lot of collisions in sparsepp. This is because the sparsepp internal array is always sized to a power of two, so when taking the modulo, only the low order bits of the hash value are retained, so in your case k.first variation is ignored => lots of collisions.

To counteract that, sparsepp used to do some "mixing" of the hash values, but there is a cost to it and it is not always useful, so I have made it optional (now it occurs only when the macro SPP_MIX_HASH is defined before including sparsepp.

In your case, I think it would be best to just change your hash function. You could rely on "hash_combine" in spp_utils.h:

```
#include <spp_utils.h>

namespace std {
  template <>
  struct hash<std::pair<uint32_t, uint32_t>>
  {
    inline uint64_t operator()(const std::pair<uint32_t, uint32_t>& k) const
    {
        uint64_t seed = (uint64_t) k.first;
        spp::hash_combine(seed, (uint64_t)k.second);
        return seed;
    }
  };
}
```

**Comment by dselivanov** [comment]
Thanks, I adjusted hash function. Seems work fine. I will perform additional tests on bigger data and report back here.

**Comment by dselivanov** [comment]
@greg7mdp unfortunately this didn't help on larger data from my benchmarks:

1. With `unordered_map` test took **39** seconds
1. With https://github.com/greg7mdp/sparsepp/tree/0fb17374eb761e31c9256bce3a63e513e846d0bc version and my old hash function (`return (uint64_t) k.first << 32 | k.second;`) it took **26.5** seconds
1. With https://github.com/greg7mdp/sparsepp/tree/48fc88160011dff87030f992d7c0afc874c7350f and with `hash_combine` I **killed after 5 minutes**

**Comment by greg7mdp** [comment]
@dselivanov, can you try using the recent sparsepp, your old hash function, and defining SPP_MIX_HASH
either on the compiler command line or before including sparsepp.h?

Is that does not help, I can provide the code to have the same hash result as the previous version.

**Comment by greg7mdp** [comment]
@dselivanov, in case the SPP_MIX_HASH above does not help:

Using the recent version of sparsepp, and **no** preprocessor macro, the following hash function should restore the behavior of the older sparsepp.

```
namespace std {
  template <>
  struct hash<std::pair<uint32_t, uint32_t>>
  {
    inline uint64_t operator()(const std::pair<uint32_t, uint32_t>& k) const
    {
        uint64_t h =  (uint64_t)k.first << 32 | k.second;
        h ^= (h >> 33);
        h ^= (h >> 17);
        return h ^ (h >> 7);
    }
  };
}
```

**Comment by dselivanov** [comment]
`SPP_MIX_HASH ` mixing helped - 26 seconds now. 
So I just add `SPP_MIX_HASH` before including `sparsepp.h`
```c++
#define SPP_MIX_HASH
#include <sparsepp.h>
```
Thank you very much for help. Closing...
