### ISSUE TITLE
Compute memory usage

### ISSUE THREAD

**Issue by N1cotin** [greg7mdp/sparsepp#37]
Hello,

is there a way (it doesn't matter how fast) to compute the exact memory usage of one hashmap?
I did some experiments with the internal allocator but could not get a realistic result.

Thank you

**Comment by greg7mdp** [comment]
It would be possible to compute the number of bytes allocated by malloc, but this would not provide an accurate memory usage, because malloc has its own overhead and there can be overhead because we reallocate buffers. 

My recommendation would be to use spp::GetProcessMemoryUsed() - in sparsepp/spp_memory.h -before and after building the hash map.

Another method for an accurate measurement would be to use spp_dlalloc (which is based on dlmalloc internally), but unfortunately the API that provides memory statistics is not implemented in the current version.
