### ISSUE TITLE
Unable to create map for value type with deleted copy constructor

### ISSUE THREAD

**Issue by mohansella** [greg7mdp/sparsepp#78]
I have a buffer class as below.
```cpp
class ImmutableBuffer  //showing only an abstract. since the code is large
{

public:
	ImmutableBuffer() = default;
        virtual ~ImmutableBuffer() = default;
	void doSomeOp() {};

private:
        //restricting default copy constructors and operators.
	ImmutableBuffer& operator=(const ImmutableBuffer& from) = default;
	ImmutableBuffer(const ImmutableBuffer& from) = default;

};
```

I see that sparsepp is better than std. so, i started migrating. I have ported half of my code. but stuck at below case.

Below is a sample code with std. it compiles and works as expected.
```cpp
void main()
{
	std::unordered_map<int, ImmutableBuffer> idVsBuffer;
	auto & buff= idVsBuffer[1];
	buff.doSomeOp();
}
```

But below ported code with SparsePP not compiling.
```cpp
void main()
{
	spp::sparse_hash_map<int, ImmutableBuffer> idVsBuffer;
	auto & data = idVsBuffer[1];
	buff.doSomeOp();
}
```

What is the recommended way to achieve this?

**Comment by mohansella** [comment]
I have implemented move constructor for my buffer and then it compiles. But still not sure why it compiles with std without move constructor.

**Comment by greg7mdp** [comment]
Hi @mohansella , sorry for the delay in responding. Internally sparsepp does have to move some values, either when they are inserted in the sparse_hash_map, or sometimes when other values are inserted. This is why the values have to be copyable or movable. Implementing the move constructor is a good solution.

std::unordered_map does not have that restriction, because the values are inserted in a linked list (which also partially explains why it has a higher memory usage).
