### ISSUE TITLE
sparse_hash_map<uint32_t, uint64_t> takes more memory than sparse_hash_map<uint64_t, uint64_t>

### ISSUE THREAD

**Issue by sunnyszy** [greg7mdp/sparsepp#85]
Hi,

I'm using sparse_hash_map for its great memory efficiency. When I do a small test, I found sparse_hash_map<uint32_t, uint64_t> takes more memory than sparse_hash_map<uint64_t, uint64_t>! I wonder why this can happen given you need more bits to store uint64?

Below is my code:

```
#include <thread>
#include "sparsepp/spp.h"

using namespace std;
using spp::sparse_hash_map;

int main(void)
{
    sparse_hash_map<uint32_t, uint64_t> negative_candidate_queue;
    for (int i = 0; i < 128*1024*1024; ++i)
        negative_candidate_queue[i] = i;
    this_thread::sleep_for(std::chrono::seconds(100));
    return 0;
}
```

My test environment:
Ubuntu 18.04.3 LTS 64bit

And my results:

sparse_hash_map<uint32_t, uint64_t> resident set size after inserting 128M entries: 2.7GB
sparse_hash_map<uint64_t, uint64_t> resident set size after inserting 128M entries: 2.567GB

**Comment by greg7mdp** [comment]
Hi @sunnyszy 

Because of alignment and padding, the memory required for `std::pair<uint32_t, uint64_t>` and `std::pair<uint64_t, uint64_t>` is probably the same (you can use sizeof() to check for yourself.
What happens is that the hashing if the integers is a little different with uint32_t and uint64_t causing the small difference you see.

if you use `sparse_hash_map<uint32_t, uint32_t>` the memory usage should be less.
